// Server-side PDFs: appointment receipts and digital prescriptions.
//
// Everything is set in Noto Sans Bengali, which also carries Latin glyphs and
// the Taka sign, so Bangla names and labels render without per-run font
// switching. Fonts and the logo are vendored under assets/ (SIL OFL licence in
// assets/fonts/OFL.txt).
const path = require("path");
const PDFDocument = require("pdfkit");
const QRCode = require("qrcode");

const ASSETS = path.join(__dirname, "..", "assets");
const FONT_REGULAR = path.join(ASSETS, "fonts", "NotoSansBengali-Regular.ttf");
const FONT_BOLD = path.join(ASSETS, "fonts", "NotoSansBengali-Bold.ttf");
const LOGO = path.join(ASSETS, "logo-mark.png");

const TEAL = "#008e89";
const INK = "#17232f";
const MUTED = "#6b7785";
const LINE = "#d9e2e8";
const DANGER = "#c62828";

const LABELS = {
  en: {
    receipt: "Appointment Receipt",
    receiptNo: "Receipt no.",
    issued: "Issued",
    patient: "Patient",
    phone: "Phone",
    doctor: "Doctor",
    hospital: "Hospital",
    online: "Online video consultation",
    serial: "Serial",
    date: "Date",
    time: "Time",
    mode: "Visit",
    inPerson: "In person",
    onlineMode: "Online",
    amount: "Amount",
    method: "Payment method",
    status: "Payment status",
    txn: "Transaction ID",
    refunded: "Refunded",
    unpaidStamp: "PAY AT HOSPITAL — UNPAID",
    unpaidNote: "Please pay at the hospital reception before your visit. Show this receipt or scan the code.",
    scan: "Scan at the reception desk",
    followUp: "Follow-up visit",
    generated: "Generated by DocAppoint",
    prescription: "Prescription",
    age: "Age",
    gender: "Gender",
    reg: "Reg. no.",
    medicines: "Medicines",
    medicine: "Medicine",
    dose: "Dose",
    frequency: "Frequency",
    duration: "Duration",
    tests: "Investigations",
    advice: "Advice",
    followUpOn: "Follow-up on",
    verify: "Scan to verify this prescription",
    signature: "Signature",
    years: "yrs",
  },
  bn: {
    receipt: "অ্যাপয়েন্টমেন্ট রসিদ",
    receiptNo: "রসিদ নং",
    issued: "ইস্যুর তারিখ",
    patient: "রোগী",
    phone: "ফোন",
    doctor: "ডাক্তার",
    hospital: "হাসপাতাল",
    online: "অনলাইন ভিডিও পরামর্শ",
    serial: "সিরিয়াল",
    date: "তারিখ",
    time: "সময়",
    mode: "ধরন",
    inPerson: "সরাসরি",
    onlineMode: "অনলাইন",
    amount: "ফি",
    method: "পেমেন্ট পদ্ধতি",
    status: "পেমেন্টের অবস্থা",
    txn: "ট্রানজেকশন আইডি",
    refunded: "ফেরত",
    unpaidStamp: "হাসপাতালে পরিশোধযোগ্য — অপরিশোধিত",
    unpaidNote: "ভিজিটের আগে হাসপাতালের রিসেপশনে ফি পরিশোধ করুন। এই রসিদটি দেখান বা কোডটি স্ক্যান করুন।",
    scan: "রিসেপশনে স্ক্যান করুন",
    followUp: "ফলো-আপ ভিজিট",
    generated: "DocAppoint থেকে তৈরি",
    prescription: "ব্যবস্থাপত্র",
    age: "বয়স",
    gender: "লিঙ্গ",
    reg: "রেজি. নং",
    medicines: "ওষুধ",
    medicine: "ওষুধ",
    dose: "মাত্রা",
    frequency: "কতবার",
    duration: "কতদিন",
    tests: "পরীক্ষা",
    advice: "পরামর্শ",
    followUpOn: "পরবর্তী সাক্ষাৎ",
    verify: "যাচাই করতে স্ক্যান করুন",
    signature: "স্বাক্ষর",
    years: "বছর",
  },
};

const METHOD_LABEL = {
  en: { sslcommerz: "SSLCommerz (card / mobile banking)", demo_mobile: "Demo mobile banking", cash: "Pay at hospital (cash)" },
  bn: { sslcommerz: "SSLCommerz (কার্ড / মোবাইল ব্যাংকিং)", demo_mobile: "ডেমো মোবাইল ব্যাংকিং", cash: "হাসপাতালে নগদ" },
};

const STATUS_LABEL = {
  en: { unpaid: "Unpaid", pending: "Pending", paid: "Paid", failed: "Failed", refunded: "Refunded", partially_refunded: "Partially refunded" },
  bn: { unpaid: "অপরিশোধিত", pending: "অপেক্ষমাণ", paid: "পরিশোধিত", failed: "ব্যর্থ", refunded: "ফেরত দেওয়া হয়েছে", partially_refunded: "আংশিক ফেরত" },
};

const taka = (n) => `৳${Number(n || 0).toLocaleString("en-US")}`;

const newDoc = (title) => {
  const doc = new PDFDocument({ size: "A4", margin: 48, info: { Title: title, Author: "DocAppoint" } });
  doc.registerFont("Body", FONT_REGULAR);
  doc.registerFont("Bold", FONT_BOLD);
  doc.font("Body");
  return doc;
};

const header = (doc, title, subtitle) => {
  const top = doc.page.margins.top;
  doc.image(LOGO, doc.page.margins.left, top - 6, { width: 46 });
  doc.font("Bold").fontSize(20).fillColor(INK).text("Doc", doc.page.margins.left + 56, top, { continued: true });
  doc.fillColor(TEAL).text("Appoint");
  doc.font("Body").fontSize(9).fillColor(MUTED).text("Doctor appointments · Bangladesh", doc.page.margins.left + 56, top + 26);

  doc.font("Bold").fontSize(15).fillColor(INK).text(title, 0, top + 2, { align: "right", width: doc.page.width - doc.page.margins.right });
  if (subtitle) {
    doc.font("Body").fontSize(9).fillColor(MUTED).text(subtitle, 0, top + 24, { align: "right", width: doc.page.width - doc.page.margins.right });
  }
  const y = top + 52;
  doc.moveTo(doc.page.margins.left, y).lineTo(doc.page.width - doc.page.margins.right, y).lineWidth(1).strokeColor(LINE).stroke();
  doc.y = y + 16;
};

/** Two-column label/value rows. */
const rows = (doc, pairs, { x = doc.page.margins.left, labelWidth = 120, width = 300 } = {}) => {
  for (const [label, value] of pairs) {
    if (value === undefined || value === null || value === "") continue;
    const y = doc.y;
    doc.font("Body").fontSize(9.5).fillColor(MUTED).text(label, x, y, { width: labelWidth });
    doc.font("Bold").fontSize(10.5).fillColor(INK).text(String(value), x + labelWidth, y, { width: width - labelWidth });
    doc.moveDown(0.35);
  }
};

const footer = (doc, text) => {
  const y = doc.page.height - doc.page.margins.bottom - 14;
  doc.font("Body").fontSize(8).fillColor(MUTED).text(text, doc.page.margins.left, y, {
    width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
    align: "center",
  });
};

/**
 * Receipt for one appointment. Returns a PDFKit document (a readable stream);
 * the caller pipes it to the response and calls end() via the returned doc.
 */
const renderReceipt = async (appt, { lang = "en" } = {}) => {
  const L = LABELS[lang] || LABELS.en;
  const methods = METHOD_LABEL[lang] || METHOD_LABEL.en;
  const statuses = STATUS_LABEL[lang] || STATUS_LABEL.en;
  const doc = newDoc(`Receipt ${appt.receiptNo || ""}`);
  const left = doc.page.margins.left;
  const contentWidth = doc.page.width - left - doc.page.margins.right;

  header(doc, L.receipt, `${L.receiptNo} ${appt.receiptNo || "—"}`);

  // Serial badge on the right, details on the left.
  const boxTop = doc.y;
  doc.roundedRect(left + contentWidth - 130, boxTop, 130, 92, 10).fillColor("#eef8f7").fill();
  doc.font("Body").fontSize(10).fillColor(MUTED).text(L.serial, left + contentWidth - 130, boxTop + 12, { width: 130, align: "center" });
  doc.font("Bold").fontSize(34).fillColor(TEAL).text(`#${appt.serial ?? "—"}`, left + contentWidth - 130, boxTop + 26, { width: 130, align: "center" });

  doc.y = boxTop;
  const patient = appt.relation && appt.relation !== "self" ? `${appt.patientName} (${appt.relation})` : appt.patientName;
  rows(doc, [
    [L.issued, new Date(appt.createdAt || Date.now()).toISOString().slice(0, 10)],
    [L.patient, patient],
    [L.phone, appt.phone],
    [L.doctor, [appt.doctorName, appt.doctorSpecialty].filter(Boolean).join(" — ")],
    [L.hospital, appt.consultationMode === "online" ? L.online : appt.hospitalName || "—"],
    [L.date, appt.appointmentDate],
    [L.time, appt.appointmentTime],
    [L.mode, appt.consultationMode === "online" ? L.onlineMode : L.inPerson],
    ...(appt.type === "follow-up" ? [["", L.followUp]] : []),
  ], { width: contentWidth - 150 });

  doc.moveDown(0.8);
  const payTop = doc.y;
  doc.moveTo(left, payTop).lineTo(left + contentWidth, payTop).strokeColor(LINE).stroke();
  doc.y = payTop + 12;
  rows(doc, [
    [L.amount, taka(appt.amount)],
    [L.method, methods[appt.paymentMethod] || appt.paymentMethod],
    [L.status, statuses[appt.paymentStatus] || appt.paymentStatus],
    [L.txn, appt.transactionId],
    ...(appt.refundedAmount > 0 ? [[L.refunded, taka(appt.refundedAmount)]] : []),
  ], { width: contentWidth });

  const unpaidCash = appt.paymentMethod === "cash" && appt.paymentStatus === "unpaid";
  const qrText = [
    `DocAppoint ${appt.receiptNo}`,
    `${appt.patientName}`,
    `${appt.doctorName} | #${appt.serial}`,
    `${appt.appointmentDate} ${appt.appointmentTime}`,
    `${taka(appt.amount)} ${appt.paymentStatus === "paid" ? "PAID" : "UNPAID"}`,
  ].join("\n");
  const qr = await QRCode.toBuffer(qrText, { margin: 1, width: 360, errorCorrectionLevel: "M" });

  doc.moveDown(1);
  const qrTop = doc.y;
  doc.image(qr, left, qrTop, { width: 110 });
  doc.font("Body").fontSize(8.5).fillColor(MUTED).text(L.scan, left, qrTop + 114, { width: 110, align: "center" });

  if (unpaidCash) {
    const sx = left + 130;
    doc.save();
    doc.roundedRect(sx, qrTop + 8, contentWidth - 130, 44, 8).lineWidth(2.5).strokeColor(DANGER).stroke();
    doc.font("Bold").fontSize(16).fillColor(DANGER).text(L.unpaidStamp, sx, qrTop + 19, { width: contentWidth - 130, align: "center" });
    doc.restore();
    doc.font("Body").fontSize(9.5).fillColor(INK).text(L.unpaidNote, sx, qrTop + 62, { width: contentWidth - 130 });
  }

  footer(doc, `${L.generated} · ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC`);
  return doc;
};

/** Digital prescription with a QR code pointing at the public verify page. */
const renderPrescription = async (rx, { verifyUrl, lang = "en" } = {}) => {
  const L = LABELS[lang] || LABELS.en;
  const doc = newDoc(`Prescription ${rx._id}`);
  const left = doc.page.margins.left;
  const contentWidth = doc.page.width - left - doc.page.margins.right;

  header(doc, L.prescription, new Date(rx.issuedAt || rx.createdAt || Date.now()).toISOString().slice(0, 10));

  // Doctor block (left) + patient block (right).
  const top = doc.y;
  doc.font("Bold").fontSize(13).fillColor(INK).text(rx.doctorName, left, top, { width: contentWidth / 2 });
  doc.font("Body").fontSize(9.5).fillColor(MUTED)
    .text([rx.doctorDegree, rx.doctorSpecialty].filter(Boolean).join(" · "), { width: contentWidth / 2 })
    .text(`${L.reg} ${rx.doctorRegNo || "—"}`, { width: contentWidth / 2 })
    .text(rx.hospitalName || L.online, { width: contentWidth / 2 });
  const afterDoctor = doc.y;

  doc.y = top;
  rows(doc, [
    [L.patient, rx.patientName],
    [L.age, rx.patientAge ? `${rx.patientAge} ${L.years}` : ""],
    [L.gender, rx.patientGender],
    [L.date, rx.visitDate],
  ], { x: left + contentWidth / 2 + 10, labelWidth: 70, width: contentWidth / 2 - 10 });
  doc.y = Math.max(afterDoctor, doc.y) + 10;
  doc.moveTo(left, doc.y).lineTo(left + contentWidth, doc.y).strokeColor(LINE).stroke();
  doc.moveDown(0.8);

  // ℞ + medicines table.
  doc.font("Bold").fontSize(26).fillColor(TEAL).text("Rx", left, doc.y);
  doc.moveDown(0.2);
  const cols = [
    { key: "name", label: L.medicine, w: 0.38 },
    { key: "dose", label: L.dose, w: 0.18 },
    { key: "frequency", label: L.frequency, w: 0.22 },
    { key: "duration", label: L.duration, w: 0.22 },
  ];
  const drawRow = (cells, bold) => {
    const y = doc.y;
    let x = left;
    let height = 0;
    for (const c of cols) {
      const w = c.w * contentWidth;
      doc.font(bold ? "Bold" : "Body").fontSize(bold ? 9.5 : 10.5).fillColor(bold ? MUTED : INK);
      const h = doc.heightOfString(String(cells[c.key] ?? ""), { width: w - 8 });
      doc.text(String(cells[c.key] ?? ""), x, y, { width: w - 8 });
      height = Math.max(height, h);
      x += w;
    }
    doc.y = y + height + 6;
    doc.moveTo(left, doc.y - 3).lineTo(left + contentWidth, doc.y - 3).strokeColor(LINE).lineWidth(0.5).stroke();
  };
  drawRow(Object.fromEntries(cols.map((c) => [c.key, c.label])), true);
  for (const [i, m] of (rx.medicines || []).entries()) drawRow({ ...m, name: `${i + 1}. ${m.name}` }, false);

  const section = (title, body) => {
    if (!body || (Array.isArray(body) && body.length === 0)) return;
    doc.moveDown(0.8);
    doc.font("Bold").fontSize(11).fillColor(INK).text(title, left);
    doc.font("Body").fontSize(10.5).fillColor(INK);
    if (Array.isArray(body)) body.forEach((t) => doc.text(`• ${t}`, left + 8, doc.y, { width: contentWidth - 8 }));
    else doc.text(body, left, doc.y, { width: contentWidth });
  };
  section(L.tests, rx.tests);
  section(L.advice, rx.advice);
  if (rx.followUpDate) section(L.followUpOn, rx.followUpDate);

  // QR + signature pinned near the bottom of the page.
  const qr = await QRCode.toBuffer(verifyUrl, { margin: 1, width: 360, errorCorrectionLevel: "M" });
  const bottom = doc.page.height - doc.page.margins.bottom - 140;
  const qrY = Math.max(doc.y + 20, bottom);
  if (qrY + 130 > doc.page.height - doc.page.margins.bottom) doc.addPage();
  const y = Math.min(qrY, doc.page.height - doc.page.margins.bottom - 140);
  doc.image(qr, left, y, { width: 96 });
  doc.font("Body").fontSize(8.5).fillColor(MUTED).text(L.verify, left + 104, y + 30, { width: 160 });
  doc.font("Body").fontSize(7.5).fillColor(MUTED).text(verifyUrl, left + 104, y + 58, { width: 200 });

  const sx = left + contentWidth - 170;
  doc.moveTo(sx, y + 70).lineTo(sx + 170, y + 70).strokeColor(INK).lineWidth(0.8).stroke();
  doc.font("Bold").fontSize(10).fillColor(INK).text(rx.doctorName, sx, y + 76, { width: 170, align: "center" });
  doc.font("Body").fontSize(8.5).fillColor(MUTED).text(`${L.signature} · ${L.reg} ${rx.doctorRegNo || "—"}`, sx, y + 92, { width: 170, align: "center" });

  footer(doc, `${L.generated} · ID ${rx._id}`);
  return doc;
};

module.exports = { renderReceipt, renderPrescription };
